# Generated by Django 2.1.2 on 2018-12-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0016_auto_20181211_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, null=True)),
                ('isPositive', models.CharField(max_length=3, null=True)),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ProbabilityOfWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, null=True)),
                ('probabilityOfPositive', models.FloatField(null=True)),
                ('probabilityOfNegative', models.FloatField(null=True)),
            ],
        ),
    ]
