# Generated by Django 2.1.2 on 2018-12-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20181218_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='isPositive',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
