# Generated by Django 2.1.2 on 2018-12-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20181227_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('isPositive', models.CharField(max_length=10, null=True)),
                ('isTrain', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='isTrain',
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
