# Generated by Django 2.1.2 on 2018-10-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, null=True)),
                ('isPositive', models.CharField(max_length=3, null=True)),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('calorie', models.IntegerField(null=True)),
                ('unit_amount', models.IntegerField(null=True)),
                ('isVegetarian', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.IntegerField(default=0, null=True)),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='calorie',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isGood',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isHard',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isVegetarian',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
