# Generated by Django 2.1.2 on 2018-11-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20181031_1522'),
        ('recipes', '0006_auto_20181113_1532'),
    ]

    operations = [
    ]
