# Generated by Django 2.1.2 on 2018-11-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20181123_0538'),
        ('recipes', '0007_auto_20181125_1138'),
    ]

    operations = [
    ]
