# Generated by Django 2.1.2 on 2018-11-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_merge_20181125_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_subtitle',
            new_name='measurementUnit',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit_amount',
        ),
        migrations.AddField(
            model_name='food',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='measurementUnit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
