# Generated by Django 2.1.2 on 2018-11-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20181115_1709'),
        ('recipes', '0010_auto_20181125_1314'),
    ]

    operations = [
    ]
