# Generated by Django 2.1.2 on 2018-12-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20181216_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='count',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calorie',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='count',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calorie',
            field=models.FloatField(default=0, null=True),
        ),
    ]
