# Generated by Django 2.1.2 on 2018-12-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20181218_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='amountsOfGram',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='measuretable',
            name='technical_measure',
            field=models.FloatField(null=True),
        ),
    ]
