# Generated by Django 2.1.2 on 2018-12-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20181218_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isTrain',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
